Repository TerraMA2/satalertas-server, pull requests merged in 2020-12, with the labels that each got.

#166 Modified
  geoserver-conf/config.json.example
  package-lock.json
  package.json
  services/report.service.js
Labels: bug, enhancement

#169 Correcting filter, removing project filter and changing it to default
  services/geoServer.service.js
  utils/helpers/geoserver/burned.filter.js
Labels: enhancement

#170 Fixed burnlight report conclusion
  services/report.service.js
  utils/helpers/report/doc-definition-queimada.js
Labels: bug

#171 Fixed bug on the PRODES 2014 image from synthesis
  services/config.service.js
  services/view.service.js
Labels: bug

#173 Add two new endpoints and fix some typos
  controllers/geoserver.js
  geoserver-conf/views/mosaic/mosaicFeatureType.json
  routes/geoserver.js
  services/geoServer.service.js
Labels: enhancement

#174 Fixing some issues at burning report
  utils/helpers/report/doc-definition-queimada.js
Labels: enhancement
