Repository TerraMA2/satalertas-server, pull requests merged in 2021-08, with the labels that each got.

#230 Refactoring on report
  README.md
  app.js
  controllers/config.controller.js
  controllers/report.controller.js
  controllers/synthesis.controller.js
  routes/config.router.js
  routes/report.route.js
  routes/synthesis.route.js
  services/config.service.js
  services/geoServer.service.js
  services/report.service.js
  services/synthesis.service.js
Labels: enhancement

#231 B2.0.0 dev
  services/synthesis.service.js
Labels: enhancement

#232 Renamed burnlight to firespot
  charts/FiringCharts.js
  controllers/synthesis.controller.js
  routes/synthesis.route.js
  services/report.service.js
Labels: enhancement

#233 B2.0.0 dev
  migrations/20210728171141-create-columns-rel-group-views.js
  models/RelGroupView.model.js
  services/report.service.js
Labels: bugfix

#234 Refactoring
  app.js
  controllers/biome.controller.js
  controllers/car.controller.js
  controllers/city.controller.js
  controllers/config.controller.js
  controllers/conservation-unit.controller.js
  controllers/error.controller.js
  controllers/geoserver.controller.js
  controllers/indigenous-land.controller.js
  controllers/info-columns.controller.js
  controllers/projus.controller.js
  controllers/report.controller.js
  controllers/sat-veg.controller.js
  controllers/view.controller.js
  models/RegisteredView.model.js
  models/report.model.js
  package-lock.json
  package.json
  routes/biome.router.js
  routes/car.router.js
  routes/city.router.js
  routes/config.router.js
  routes/conservation-unit.router.js
  routes/geoserver.route.js
  routes/indigenous-land.router.js
  routes/indigenousLand.router.js
  routes/info-columns.router.js
  routes/projus.router.js
  routes/report.route.js
  routes/sat-veg.route.js
  routes/view.route.js
  services/biome.service.js
  services/car.service.js
  services/city.service.js
  services/conservation-unit.service.js
  services/indigenous-land.service.js
  services/info-columns.service.js
  services/map.service.js
  services/projus.service.js
  services/report.service.js
  services/synthesis.service.js
  services/view.service.js
Labels: enhancement

#235 B2.0.0 dev
  services/group-view.service.js
Labels: enhancement

#236 Refactoring on dashboard
  controllers/dashboard.controller.js
  controllers/geoserver.controller.js
  enum/layerType.js
  enum/layerTypeName.js
  routes/dashboard.router.js
  services/dashboard.service.js
  utils/filter/filter.utils.js
  utils/geoServer.utils.js
Labels: enhancement

#237 Fixed report sql
  services/report.service.js
Labels: bug

#239 Fixed downloaded reports select
  controllers/report.controller.js
Labels: bug

#240 B2.0.0 dev
  charts/FiringCharts.js
  controllers/group-view.controller.js
  controllers/view.controller.js
  migrations/20210108031319-create-group.js
  migrations/20210108143800-create-rel-group-view.js
  migrations/20210728171141-create-columns-rel-group-views.js
  migrations/20210728193803-alter-columns-rel-group-views.js
  models/DataSeries.model.js
  models/DataSet.model.js
  models/DataSetFormat.model.js
  models/Group.model.js
  models/RegisteredView.model.js
  models/View.model.js
  models/biome.model.js
  models/car.model.js
  models/city.model.js
  models/conservation-unit.model.js
  models/dataSeries.model.js
  models/dataSet.model.js
  models/dataSetFormat.model.js
  models/group.model.js
  models/index.js
  models/indigenous-land.model.js
  models/project.model.js
  models/projus.model.js
  models/registeredView.model.js
  models/relGroupView.model.js
  models/report.model.js
  models/view.model.js
  package-lock.json
  package.json
  routes/group-view.router.js
  services/analyze.service.js
  services/biome.service.js
  services/car.service.js
  services/city.service.js
  services/conservation-unit.service.js
  services/dashboard.service.js
  services/group-view.service.js
  services/group.service.js
  services/indigenous-land.service.js
  services/map.service.js
  services/projus.service.js
  services/report.service.js
  services/synthesis.service.js
  services/view.service.js
  utils/filter/filter.utils.js
  utils/geoServer.utils.js
  utils/helpers/geoserver/assemblyLayer.js
  utils/view.utils.js
Labels: enhancement, new feature, bugfix

#241 Refactoring getByGroupId
  services/group-view.service.js
Labels: enhancement, bugfix

#242 Added login
  app.js
  controllers/auth.controller.js
  models/user.model.js
  package-lock.json
  package.json
  routes/auth.route.js
  services/auth.service.js
Labels: enhancement

#243 Fix typo
  services/report.service.js
Labels: bug

#245 Duplicates ' at municipio cql filter
  services/report.service.js
Labels: bugfix
