Repository TerraMA2/satalertas-server, pull requests merged in 2021-07, with the labels that each got.

#216 Some text Changes
  utils/helpers/report/doc-definition-queimada.js
Labels: bugfix

#218 Refactoring
  controllers/report.js
  routes/report.js
  services/report.service.js
  utils/messageError.js
Labels: bug

#219 Resolving conflicts
  package.json
  services/map.service.js
  services/report.service.js
  utils/logger.js
Labels: bugfix

#220 Some changes at reports
  geoserver-conf/config.json.example
  package.json
  services/report.service.js
  utils/helpers/report/doc-definition-queimada.js
Labels: enhancement

#221 B1.0.1 - Migrating firing charts to BE
  app.js
  bin/www
  charts/FiringCharts.js
  charts/SatAlertasChart.model.js
  config/config.json.example
  package-lock.json
  package.json
  services/report.service.js
  utils/Enums.js
  utils/helpers/report/doc-definition-queimada.js
Labels: enhancement

#222 Bug fix -
  charts/FiringCharts.js
Labels: bugfix

#223 B2.0.0 dev
  app.js
  bin/www
  config/config.json.example
  controllers/config.js
  controllers/group.controller.js
  controllers/report.js
  controllers/view.js
  geoserver-conf/config.json.example
  models/DataSeries.model.js
  models/DataSet.model.js
  models/DataSetFormat.model.js
  models/Group.model.js
  models/Project.model.js
  models/RegisteredView.js
  models/RelGroupView.model.js
  models/View.model.js
  models/project.model.js
  package-lock.json
  package.json
  routes/config.js
  routes/group.router.js
  routes/report.js
  routes/view.js
  services/analyze.service.js
  services/config.service.js
  services/dashboard.service.js
  services/group-view.service.js
  services/group.service.js
  services/map.service.js
  services/report.service.js
  services/view.service.js
  utils/Enums.js
  utils/helpers/geoserver/assemblyLayer.js
  utils/helpers/report/doc-definition-deter.js
  utils/helpers/report/doc-definition-prodes.js
  utils/helpers/report/doc-definition-queimada.js
  utils/logger.js
  utils/view.utils.js
Labels: enhancement

#224 Fix setCharts bug
  services/report.service.js
Labels: bugfix

#225 Migrations
  charts/FiringCharts.js
  charts/SatAlertasChart.model.js
  migrations/20210728171141-create-columns-rel-group-views.js
  migrations/20210728193803-alter-columns-rel-group-views.js
Labels: enhancement

#227 Fixed migrations
  migrations/20210108031319-create-group.js
  migrations/20210728171141-create-columns-rel-group-views.js
  migrations/20210728193803-alter-columns-rel-group-views.js
  package-lock.json
  package.json
  services/group-view.service.js
Labels: bug

#228 Refactoring
  charts/FiringCharts.js
  charts/SatAlertasChart.model.js
  controllers/config.controller.js
  routes/config.js
  services/analyze.service.js
  services/car.service.js
  services/config.service.js
  services/group-view.service.js
  services/group.service.js
  services/map.service.js
  services/report.service.js
  utils/export.utils.js
  utils/geoServer.utils.js
  utils/helpers/report/doc-definition-prodes.js
  utils/view.utils.js
Labels: enhancement

#229 Fixes migrations issues
  migrations/20191220125412-create-report.js
  migrations/20210108031319-create-group.js
  migrations/20210108143800-create-rel-group-view.js
  migrations/20210728171141-create-columns-rel-group-views.js
  migrations/20210728193803-alter-columns-rel-group-views.js
Labels: bugfix
