Repository TerraMA2/satalertas-server, pull requests merged in 2021-01, with the labels that each got.

#176 Adding 2.0.0- to version key at package.json
  package-lock.json
  package.json
Labels: enhancement

#177 Fixed logs folder permission error
  utils/logger.js
Labels: bug

#178 Backend-Routs of the group management
  app.js
  controllers/group.controller.js
  migrations/20210108031319-create-group.js
  migrations/20210108143716-create-group-view.js
  migrations/20210108143800-create-rel-group-view.js
  models/group.js
  models/project.model.js
  models/rel-group-view.model.js
  models/view.js
  routes/group.router.js
  services/group.service.js
  utils/logger.js
Labels: new feature

#181 Group routes
  controllers/group.controller.js
  migrations/20210108031319-create-group.js
  migrations/20210108143800-create-rel-group-view.js
  models/group.js
  models/rel-group-view.model.js
  routes/group.router.js
  services/group.service.js
Labels: enhancement

#182 Fixed models table name
  geoserver-conf/config.json.example
  models/group.js
  models/rel-group-view.model.js
  services/group.service.js
Labels: bug

#183 Update migrations
  migrations/20210108031319-create-group.js
  migrations/20210108143800-create-rel-group-view.js
Labels: bug

#184 modifying the update method so that it receives or group id delete the information contained in it
  controllers/group-view.controller.js
  models/rel-group-view.model.js
  services/group-view.service.js
  services/group.service.js
Labels: enhancement

#185 Added sequelize migration up to the initialization
  bin/www
  migrations/20210108143800-create-rel-group-view.js
  models/index.js
  package.json
  utils/geoServer.utils.js
Labels: enhancement

#186 Inserting the selected groups into the database
  services/group-view.service.js
Labels: enhancement
