Repository TerraMA2/satalertas-server, pull requests merged in 2021-09, with the labels that each got.

#246 B2.0.0 dev
  charts/FiringCharts.js
  config/config.json.example
  controllers/group-view.controller.js
  controllers/info-columns.controller.js
  controllers/map.controller.js
  controllers/view.controller.js
  migrations/20210108143800-create-rel-group-view.js
  migrations/20210728193803-alter-columns-rel-group-views.js
  migrations/20210826155605-create-infocolumns-table-list.js
  migrations/20210826181017-create-infocolumns-columns-list.js
  migrations/20210826214140-create-secondary-types.js
  models/dataSet.model.js
  models/index.js
  models/infocolumnsColumnsList.js
  models/infocolumnsTableList.js
  models/secondaryTypes.js
  models/view.model.js
  package-lock.json
  package.json
  routes/info-columns.router.js
  seeders/20210826190455-get-tables-from-view.js
  seeders/20210826211755-get-colums.js
  seeders/20210826222620-infocolumns-columns-list-seed.js
  seeders/20210826222624-seed-secondary-types.js
  services/car.service.js
  services/dashboard.service.js
  services/group-view.service.js
  services/group.service.js
  services/info-columns.service.js
  services/map.service.js
  services/report.service.js
  services/view.service.js
  utils/filter/filter.utils.js
  utils/helpers/geoserver/assemblyLayer.js
  utils/messageError.js
  utils/result.js
  utils/tool.js
  utils/view.utils.js
Labels: enhancement, new feature, bugfix

#248 Added geoserver basePath
  config/config.json.example
  services/geoServer.service.js
  services/report.service.js
  services/view.service.js
  utils/helpers/geoserver/assemblyLayer.js
Labels: enhancement

#249 Change Prodes image to Planet (latest)
  services/report.service.js
Labels: enhancement

#250 Bug fix - image not found
  services/report.service.js
Labels: bugfix

#251 Fixed geoserver config variables
  package-lock.json
  services/report.service.js
Labels: bug

#252 Reverting
  services/report.service.js
Labels: bugfix

#253 Changes report PRODES image to planet_latest
  services/report.service.js
Labels: enhancement

#255 Removed view.utils
  services/class.service.js
  services/dashboard.service.js
  services/info-columns.service.js
  services/report.service.js
  services/synthesis.service.js
  services/view.service.js
  utils/view.utils.js
Labels: enhancement

#256 Renamed ndvi images
  services/report.service.js
Labels: enhancement

#258 B2.0.0 dev
  controllers/group-view.controller.js
  models/group.model.js
  routes/info-columns.router.js
  seeders/20210826211755-get-colums.js
  seeders/20210826222620-infocolumns-columns-list-seed.js
  seeders/20210826222624-seed-secondary-types.js
  seeders/auxyliarytables.json
  services/group-view.service.js
  utils/helpers/views/filter/new_filter.js
Labels: enhancement

#260 Refactoring on the report
  controllers/report.controller.js
  migrations/20191220125412-create-report.js
  package-lock.json
  package.json
  routes/report.route.js
  services/report.service.js
Labels: enhancement

#261 Refactoring to QuickChart use ChartJs 3
  charts/chart.js
Labels: bugfix

#262 Refactoring
  package-lock.json
  package.json
  services/geoServer.service.js
  services/report.service.js
  services/synthesis.service.js
Labels: enhancement

#263 Geoserver image retrieve from geosrver-api
  services/report.service.js
Labels: enhancement

#265 Synthesis refactoring
  controllers/synthesis.controller.js
  routes/synthesis.route.js
  services/geoServer.service.js
  services/synthesis.service.js
Labels: enhancement

#266 Added chart generation to the synthesis
  services/car.service.js
  services/report.service.js
  services/synthesis.service.js
Labels: enhancement

#267 Fixed report generation
  services/report.service.js
  utils/helpers/report/doc-definition-deter.js
  utils/helpers/report/doc-definition-prodes.js
  utils/helpers/report/doc-definition-queimada.js
Labels: bug

#268 Fix typos and refactoring
  .editorconfig
  services/report.service.js
  utils/helpers/report/doc-definition-deter.js
Labels: enhancement, bugfix

#269 Report geoserver image from front end
  package-lock.json
  package.json
  services/geoServer.service.js
  services/report.service.js
Labels: enhancement

#270 Refactoring
  services/report.service.js
  utils/helpers/report/doc-definition-deter.js
  utils/helpers/report/doc-definition-prodes.js
  utils/helpers/report/doc-definition-queimada.js
Labels: enhancement

#271 Refactoring on the download pdf
  services/report.service.js
  utils/helpers/report/doc-definition-deter.js
  utils/helpers/report/doc-definition-prodes.js
  utils/helpers/report/doc-definition-queimada.js
Labels: enhancement

#272 Added number format to the report
  package-lock.json
  package.json
  services/report.service.js
  utils/formatter.utils.js
  utils/helpers/report/doc-definition-deter.js
  utils/helpers/report/doc-definition-prodes.js
Labels: enhancement

#273 Migrates some functions from client to server
  package-lock.json
  services/report.service.js
  utils/deter-tools.js
  utils/image-handler.js
  utils/prodes-tools.js
Labels: enhancement, bugfix
